# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana-oss:6.2.1

ADD kibana-time-plugin /usr/share/kibana/plugins/kibana-time-plugin

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
